export default {
  SERVER_PORT: 8080,
  ACCESS_TOKEN_PRIVATE_KEY: "PKQYJz+dyvGPJZeD+jrexNTZphWo4j6xyyUoDJUToOT4=",
  REFRESH_TOKEN_PRIVATE_KEY: "XQlqYovTJ2TeB1Cj5/1kGZ07Jo1XUs5FExYzKPNPc6k=",
};
