export const TOKEN = {
  ACCESS_TOKEN_PRIVATE_KEY: "PKQYJz+dyvGPJZeD+jrexNTZphWo4j6xyyUoDJUToOT4=",
  REFRESH_TOKEN_PRIVATE_KEY: "XQlqYovTJ2TeB1Cj5/1kGZ07Jo1XUs5FExYzKPNPc6k=",
  SALT_ROUNDS: 10,
  ACCESS_TOKEN_EXP: "10m",
  REFRESH_TOKEN_EXP: "23h",
};
